#!/bin/bash

VERSION=$1
RELEASE_DIR=$2

arch="$(lscpu | grep Arch | awk '{print $2}')"
if [ "${arch}" == "x86_64" ]; then
	PLATFORM=linux64
else
	PLATFORM=linux32
fi
APP="$(realpath .)"
RELEASE_DIR=$(realpath "${RELEASE_DIR}")
FINAL=${APP}/target/final
TMP=${APP}/target/tmp
TMPAPP=${TMP}/turtl-${PLATFORM}/turtl

function cleanup() {
	rm -rf ${TMP}
}
trap cleanup exit

if [ ! -d ${FINAL} ]; then
	echo "Creating ${FINAL}..."
	mkdir -p ${FINAL}
fi

pushd ${FINAL} > /dev/null || {
	echo "Error entering directory ${FINAL}."
	exit 1
}

mkdir -p ${TMPAPP}

rsync -avzz \
	--delete \
	--delete-excluded \
	${RELEASE_DIR}/ \
	${TMPAPP}/

pushd ${TMP}
cp ${APP}/scripts/resources/favicon.128.png ${TMPAPP}/icon.png
cp ${APP}/scripts/installers/linux ${TMPAPP}/../install.sh
sed -i "s|{{platform}}|${PLATFORM}|g" ${TMPAPP}/../install.sh
pushd ${TMP}/../.. > /dev/null
tar -czf ${FINAL}/turtl-${PLATFORM}.tar.bz2 .
popd > /dev/null
rm -rf ${TMP}

