#!/bin/bash

VERSION=$1
RELEASE_DIR=$2

function realpath() {
	[[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

APP="$(realpath .)"
RELEASE_DIR=$(realpath "${RELEASE_DIR}")
FINAL=${APP}/target/final

if [ ! -d ${FINAL} ]; then
	echo "Creating ${FINAL}..."
	mkdir -p ${FINAL} || exit 1
fi

pushd ${RELEASE_DIR} > /dev/null
zip -qr -9 -X \
	${FINAL}/turtl-osx.zip \
	.
popd > /dev/null

