#!/bin/bash

VERSION=$1
RELEASE_DIR=$2

function realpath() {
	[[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

APP="$(realpath .)"
RELEASE_DIR=$(realpath "${RELEASE_DIR}")
FINAL=${APP}/target/final
TMP=${APP}/target/tmp
TMPAPP=${TMP}

function cleanup() {
	rm -rf ${TMP}
}
trap cleanup exit

if [ ! -d ${FINAL} ]; then
	echo "Creating ${FINAL}..."
	mkdir -p ${FINAL}
fi

pushd ${FINAL} > /dev/null || {
	echo "Error entering directory ${FINAL}."
	exit 1
}

mkdir -p ${TMPAPP}

rsync -avzz \
	--delete \
	--delete-excluded \
	${RELEASE_DIR}/ \
	${TMPAPP}/

pushd ${TMP} > /dev/null
zip -qr -9 -X \
	${FINAL}/turtl-osx.zip \
	. \
	-i .
popd > /dev/null

