#!/bin/bash

PLATFORM=$1
VERSION=$2

APP=`realpath .`
RELEASE="$(realpath ${APP}/release/nwjs/${PLATFORM})"
RELEASE_DIR=${APP}/release
TMP=${RELEASE}/../tmp

if [ "${PLATFORM}" == "" ]; then
	echo "Usage:"
	echo "  $0 [windows|linux32|linux64|osx]"
	exit 1
fi

if [ ! -d ${RELEASE} ]; then
	echo "Error: ${RELEASE} not present"
	exit 1
fi

pushd ${RELEASE} > /dev/null || {
	echo "Error entering directory ${RELEASE}."
	exit 1
}

mkdir -p ${TMP}

if [ "${PLATFORM}" == "linux32" ] || [ "${PLATFORM}" == "linux64" ]; then
	RELNAME=turtl-${PLATFORM}
	SUBDIR=${TMP}/${RELNAME}/turtl
	mkdir -p ${SUBDIR}
	rsync -avz \
		--delete \
		--delete-excluded \
		./ \
		${SUBDIR}
	pushd ${TMP}
	cp ${RELEASE_DIR}/package.nw ${SUBDIR}
	mv ${SUBDIR}/nw ${SUBDIR}/turtl-bin

	cp ${APP}/scripts/resources/favicon.128.png ${SUBDIR}/icon.png
	cp ${APP}/scripts/resources/turtl-linux-init.sh ${SUBDIR}/turtl
	chmod 755 ${SUBDIR}/turtl

	cp ${APP}/scripts/installers/linux ${SUBDIR}/../install.sh
	sed -i "s|{{platform}}|${PLATFORM}|g" ${SUBDIR}/../install.sh
	tar -cjf ${RELEASE_DIR}/turtl-${PLATFORM}.tar.bz2 ${RELNAME}
	popd > /dev/null
elif [ "${PLATFORM}" == "windows" ]; then
	export PATH="$PATH:/d/dev/wix"
	SUBDIR=${TMP}/windows
	rsync -avz \
		--delete \
		--delete-excluded \
		./ \
		${SUBDIR}
	pushd ${TMP}
	cp ${RELEASE_DIR}/package.nw ${SUBDIR}
	cp ${APP}/scripts/resources/favicon.ico ${SUBDIR}/turtl.ico
	cp ${APP}/scripts/resources/installer_banner.bmp .
	${APP}/scripts/to-rtf.sh ${APP}/LICENSE > license.rtf
	cat ${APP}/scripts/installers/windows.wxs \
		| sed "s/{{VERSION}}/${VERSION}/g" \
		> turtl.wxs
	mv ${SUBDIR}/nw.exe ${SUBDIR}/turtl.exe
	heat \
		dir \
		windows \
		-o turtl-files.wxs \
		-scom -frag -srd -sreg -gg \
		-cg TurtlFileGroup \
		-dr APPLICATIONFOLDER
	candle -arch x64 turtl.wxs turtl-files.wxs
	light turtl.wixobj turtl-files.wixobj -ext WixUIExtension -b windows -o turtl-windows.msi
	mv turtl-windows.msi ${RELEASE_DIR}/
	popd > /dev/null
elif [ "${PLATFORM}" == "osx" ]; then
	rsync -avz \
		--exclude='nwjc' \
		--delete \
		--delete-excluded \
		./ \
		${TMP}
	pushd ${TMP}
	mv nwjs.app Turtl.app
	mv Turtl.app/Contents/MacOS/nwjs Turtl.app/Contents/MacOS/turtl
	sed -i '/<key>CFBundleIdentifier<\/key>/!b;n;c<string>com.lyonbros.turtl</string>' Turtl.app/Contents/Info.plist
	sed -i '/<key>CFBundleDisplayName<\/key>/!b;n;c<string>Turtl</string>' Turtl.app/Contents/Info.plist
	sed -i '/<key>CFBundleName<\/key>/!b;n;c<string>Turtl</string>' Turtl.app/Contents/Info.plist
	sed -i '/<key>CFBundleIdentifier<\/key>/!b;n;c<string>com.lyonbros.turtl</string>' Turtl.app/Contents/Info.plist
	sed -i '/<key>CFBundleExecutable<\/key>/!b;n;c<string>turtl</string>' Turtl.app/Contents/Info.plist
	sed -i "/<key>CFBundleShortVersionString<\/key>/!b;n;c<string>${VERSION}</string>" Turtl.app/Contents/Info.plist
	cp ${RELEASE_DIR}/package.nw Turtl.app/Contents/Resources/app.nw
	cp ${APP}/scripts/resources/favicon.128.icns Turtl.app/Contents/Resources/app.icns
	genisoimage.exe -V "Turtl-${VERSION}" -D -R -apple -no-pad -o ${RELEASE_DIR}/turtl-${PLATFORM}.dmg Turtl.app/
	popd > /dev/null
fi

# DEBUG: remove
#rm -rf ${TMP}

popd > /dev/null
