#!/bin/bash

### This script generates index.html, which loads all needed javascript and
### css for the app.

pwd=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $pwd/../data/app

ASSET_ROOT="app://turtl/data/app/"
SEARCH_PATH=""
source "$pwd/../data/app/scripts/include.sh"

## -----------------------------------------------------------------------------
## generate extra
## -----------------------------------------------------------------------------
extra='<base href="app/">'
extra="${extra}\n<link rel=\"shortcut icon\" href=\"app://turtl/data/app/images/favicon.png\" type=\"image/png\">"

## -----------------------------------------------------------------------------
## generate CSS links
## -----------------------------------------------------------------------------
css="$(
	echo "$(all_css)" \
		| sed 's|^|<link rel=\"stylesheet\" href=\"|' \
		| sed 's|$|">|'
)"

## -----------------------------------------------------------------------------
## generate JS includes
## -----------------------------------------------------------------------------
js="$(
	echo "$(all_js)" \
		| sed 's|___| |g' \
		| sed 's|^|<script src="|' \
		| sed 's|$|"></script>|'
)"

for x in $(find $pwd/../data/controllers -name "*.js"); do
	x=$(basename $x)
	js="${js}$(print_js "../controllers/$x")"
done
js="${js}\n<script src=\"app://turtl/config.js\"></script>"
js="${js}\n<script src=\"app://turtl/tools.js\"></script>"
js="${js}\n<script src=\"app://turtl/comm.js\"></script>"
js="${js}\n<script src=\"app://turtl/popup.js\"></script>"
js="${js}\n<script src=\"app://turtl/notifications.js\"></script>"
js="${js}\n<script src=\"app://turtl/pairing.js\"></script>"
js="${js}\n<script src=\"app://turtl/dispatch.js\"></script>"
js="${js}\n<script src=\"app://turtl/main.js\"></script>"


## -----------------------------------------------------------------------------
## put it all together
## -----------------------------------------------------------------------------
index="$(cat $pwd/../data/app/views/layouts/default.html)"
index="$(do_replace "$index" '{{extra}}' "$extra")"
index="$(do_replace "$index" '{{gencss}}' "$css")"
index="$(do_replace "$index" '{{genjs}}' "$js")"

# send our generated data into their restecpive files
echo -ne "$index" > $pwd/../data/index.html

# gen popup/index.html
index="$(cat $pwd/../data/popup/index.html.tpl)"
index="$(do_replace "$index" '{{extra}}' "$extra")"
index="$(do_replace "$index" '{{gencss}}' "$css")"
index="$(do_replace "$index" '{{genjs}}' "$js")"

# send our generated data into their restecpive files
echo -ne "$index" > $pwd/../data/popup/index.html
