#!/bin/bash

### This script generates index.html, which loads all needed javascript and
### css for the app.

TEMPLATE=$1

if [ "$TEMPLATE" == "" ]; then
	TEMPLATE="main"
fi

pwd=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $pwd/../${BUILD}/app

ASSET_ROOT="/${BUILD}/app/"
SEARCH_PATH=""
source "$pwd/../${BUILD}/app/scripts/include.sh"

## -----------------------------------------------------------------------------
## generate extra
## -----------------------------------------------------------------------------
extra="<base href=\"./app/\">"

## -----------------------------------------------------------------------------
## generate CSS links
## -----------------------------------------------------------------------------
css="$(
	echo "$(all_css)" \
		| sed 's|^|<link rel=\"stylesheet\" href=\"|' \
		| sed 's|$|">|'
)"

## -----------------------------------------------------------------------------
## generate JS includes
## -----------------------------------------------------------------------------
js="$(
	echo "$(all_js)" \
		| sed 's|___| |g' \
		| sed 's|^|<script src="|' \
		| sed 's|$|"></script>|'
)"
vendorjs="$(
	echo "$(vendor_js)" \
		| sed 's|___| |g' \
		| sed "s|^|<script src="'"'"/${BUILD}/app/|" \
		| sed 's|$|"></script>|'
)"

for x in $(find $pwd/../lib/app/ -name "*.js" | sort | grep -v 'popup/'); do
	x=$(echo $x | sed 's|.*/lib/app/||')
	ASSET_ROOT= js="${js}$(print_js "../../lib/app/$x")"
done
js="${js}\n<script src=\"../config.js\"></script>"

## -----------------------------------------------------------------------------
## put it all together
## -----------------------------------------------------------------------------
if [ "$TEMPLATE" == "main" ]; then
	index="$(cat $pwd/../${BUILD}/app/views/layouts/default.html)"
	index="$(do_replace "$index" '{{extra}}' "$extra")"
	index="$(do_replace "$index" '{{gencss}}' "$css")"
	index="$(do_replace "$index" '{{genjs}}' "$js")"

	echo -ne "$index"
fi

if [ "$TEMPLATE" == "popup" ]; then
	index="$(cat $pwd/../lib/app/popup/index.html.tpl)"
	index="$(do_replace "$index" '{{extra}}' "$extra")"
	index="$(do_replace "$index" '{{gencss}}' "$css")"
	index="$(do_replace "$index" '{{genjs}}' "$js")"
	index="$(do_replace "$index" '{{vendorjs}}' "$vendorjs")"

	echo -ne "$index"
fi

